### ISSUE TITLE
Support optional fields for allOf field object

### ISSUE THREAD

**Issue by prabhpreet** [kurtbuilds/libninja#14]
EDIT: See below comment for clarification

Fields by default are optional in OpenAPI 3, unless mentioned in the `required` section of the object.

Currently, ~~all fields are mandatory~~ optional fields of objects defined as an allOf field is mandatory in the generated code. I had to manually make the fields optional by changing the structs fields to `Option<T>`.

**Comment by kurtbuilds** [comment]
Can you share where you're seeing this? Please provide an example OpenAPI spec, the generated libninja code, and point out the errors.

I'd need to look up examples, but from what I've seen in real world specs, I believe many specs have always-present data, at the very least in responses, even though the fields aren't technically marked as required, so it's absurdly pedantic to make all those fields optional. Perhaps libninja could have a `strict` mode that would generate them as option.

**Comment by prabhpreet** [comment]
Actually, my bad- most fields are marked optional unless they are marked required. I encountered an edge case where I use an `allOf` and specify an object as one of the object definitions (rather than referencing it). 

I have created an example here: https://github.com/prabhpreet/libninja-allof-example/ with the spec https://github.com/prabhpreet/libninja-allof-example/blob/main/petstore.yaml

Consider the `PetTag` object in the spec below:

https://github.com/prabhpreet/libninja-allof-example/blob/28fbbfeefc25b0b5653d4b36fba7f32e2d0ecd3e/petstore.yaml#L85-L119

The field `weight` in the object is not required but is not wrapped in an `Option` enum in the generated code. However, if I reference an entire object (eg. here `PetHealth`'s optional field `neutered` here), the entire object does wrap the optional fields correctly.

https://github.com/prabhpreet/libninja-allof-example/blob/28fbbfeefc25b0b5653d4b36fba7f32e2d0ecd3e/src/model/pet_tag.rs#L5-L13


https://github.com/prabhpreet/libninja-allof-example/blob/28fbbfeefc25b0b5653d4b36fba7f32e2d0ecd3e/src/model/pet_health.rs#L4-L8

**Comment by kurtbuilds** [comment]
Got it. Just to confirm, is there an error here? To my eye, those structs look like they conform correctly to that OpenAPI spec.

**Comment by prabhpreet** [comment]
I think this is an error since it is making an optional field in the spec into required in the struct.

Just to recap, specifically the error is when one of the object types in an `allOf` spec has an optional field (not mentioned in the required section of the object type). This field is not mapped as an `Option` in the struct, making it a required field.

**Comment by kurtbuilds** [comment]
Thank you for clarifying. Fixed with regression tests, and bumped version to 0.1.10.

**Comment by prabhpreet** [comment]
Thanks for the prompt fix!
