### ISSUE TITLE
Error: Failed to deserialize OpenAPI spec when attempting to generate cilium client

### ISSUE THREAD

**Issue by bhechinger** [kurtbuilds/libninja#18]
I fetched the Cilium OAS from here: https://raw.githubusercontent.com/cilium/cilium/v1.14.4/api/v1/openapi.yaml

Running libninja fails with this error:
```
$ libninja gen --lang rust --repo bhechinger/cilium-rs -o . Cilium openapi.yaml
Error: Failed to deserialize OpenAPI spec.

Caused by:
    data did not match any variant of untagged enum ReferenceOr
```

**Comment by kurtbuilds** [comment]
This appears to be a swagger 2.0 spec. Libninja doesn't yet support reading 2.0 specs.

You can use online tools, or the underlying openapi library, to upgrade the spec. See here for an example: https://github.com/kurtbuilds/openapiv3/blob/master/tests/test_v2.rs

I'd welcome a PR to conditionally read 2 or 3 API specs.

**Comment by bhechinger** [comment]
Ah ha! That was an easy thing to fix as well.

```
curl -s https://converter.swagger.io/api/convert\?url\=https://raw.githubusercontent.com/cilium/cilium/${CILIUM_VERSION}/api/v1/openapi.yaml -o openapi.json
```
Perfect, thanks for the great work!

**Comment by bhechinger** [comment]
So I quickly ran into this issue trying to build:

```
error[E0599]: no method named `authenticate` found for reference `&'a CiliumClient` in the current scope
  --> /home/wonko/projects/Payrails/cilium-rs/src/request/get_ip.rs:29:29
   |
29 |             r = self.client.authenticate(r);
   |                             ^^^^^^^^^^^^ method not found in `&CiliumClient`
```

You can find the generated code here: https://github.com/bhechinger/cilium-rs

**Comment by kurtbuilds** [comment]
Apologies for that. It should be fixed on master.

Is it meant to have authentication built in? That code erroring would indicate that it's not generating any authentication code for the API - not sure if that's what you intend.

**Comment by bhechinger** [comment]
That fixes the errors, thanks!

You removed the `--version` flag, was that intentional?

Is there meant to have authentication built in? Honestly I wish I knew. I've been all over the documentation and it's not real clear on that. I'm assuming it's using k8s for auth.

**Comment by bhechinger** [comment]
Ok, so it's become more clear after asking on the Cilium slack. This API integrates into kube-apiserver so it's using the authentication built into that. I need to figure out how to extend kube-rs with this.

Thanks for all your help!

**Comment by kurtbuilds** [comment]
Good point on version.

I added logic to auto-increment the version, but I'll add the override flag back in. (Likewise, --repo is now optional, whereas it was needlessly required before.)

Re-added the flag in d10c5a4
