### ISSUE TITLE
Flag to disable example generation

### ISSUE THREAD

**Issue by ju6ge** [kurtbuilds/libninja#6]
Hey,

I tried using this to generate a rust client for an openapi spec. Sadly it fails at the stage of generating examples. Could you add a flag to the tool, to skip this? Not all paths have examples provided and it would be convenient for testing purposes to just disable that if it is not desired.

Kind regards,
ju6ge

**Comment by kurtbuilds** [comment]
Great call. Yeah this can be added without too much effort. Busy week but I'll try to tackle it this week. Welcome a PR for it.

**Comment by ju6ge** [comment]
My week is pretty full as well. If it had been obvious to me at which point to best add it I would have done it directly and send a PR ;). I might have some time on thursday to take a deeper look at it. 

Anyway great to here this is a welcome addition. Have a nice week 👍

**Comment by ju6ge** [comment]
So I was able to disable the example generation. There was still an error at the end, and the resulting library does not build. But that might be due to assumptions of how this crate operates. I need to do some more digging. If I am sure the failures are not due to my patches I will send a PR, for this feature.

**Comment by ju6ge** [comment]
So I just finished up the generate example flag.

I have noticed many things, that make this library hard to use:
- First of, it assumes that there is authentication. For the simple case I am testing that is not the case. So I have to manually remove it. This also means that this library will fail to build the most simple example case from OpenApi itself. Would be great if that is detected.
- Secondly, it assumes that all responses will be in json. This is not the case for every Api, all calls that do not return a json have an empty in Memory result, which makes them unusable! Apart from that for those calls that do return a json it returns Value instead of a more detailed structure. Which should be possible since the code for the request types is there and works!

 Both of these seem like things that require a lot more work. Should I create Issues for them?

Anyway I also wanted to thank you for the work you already put into this. You correctly stated that openapi is very complex, and that means creating something like this generator is very hard! I like the approach you have taken so far.

**Comment by kurtbuilds** [comment]
You're right about the authentication. I consider that a bug.

Want to be sure I understand what you're saying about the JSON. Are you specifically talking about responses that are empty? That's definitely another bug.

Happy to chat about approach needed to fix either or both of those issues.

And thank you!

**Comment by ju6ge** [comment]
Well OpenApi is designed around JSON, but that does not mean that the API it is describing has to always respond in JSON. The OpenApi Specification allows for the response to have any content-type. My use case here is that I have API calls that depending on the sent `Accept` in the request. Will answer with the corresponding 'Content-Type`. Which content-types are supported by the specific API endpoint is clear from the spec, because it is possible to define multiple possible responses with OpenApi. Swagger does support this, but I am aware that this is a more complicated use case. But given the power of rusts type system it should be possible to map this behavior correctly.

**Comment by kurtbuilds** [comment]
Got it. Yeah this definitely could include support for other data types.

I think there are important questions about how that would work. Like would you want to create clients that are generic on the return type, if the accept type can be specified? It sounds like that would lead to a combinatorial explosion with a naive implementation.

Do you have a sketch in mind already for how support for multiple encoding types might work?

To set expectations, building support for this would be a sizeable undertaking. It's not something I would have bandwidth to tackle, but I'm certainly open to PRs and offering guidance on how to implement it if you're willing to undertake it.

**Comment by ju6ge** [comment]
Yes you are absolutely right that this would be a major undertaking! So I am not suggesting it needs to be done right now or anything. My bandwith is also limited at the moment. Probably it is something that I could only work on bit by bit, and of course I would need to do a deep dive in your code generation implementation to even know where to begin. My intuition would suggest to do it via enum types for the responses if multiple responses are possible.

Regarding the first issue of optional authentication, this would probably be something I could do first, to get my feet wet deeper in the codebase.

**Comment by kurtbuilds** [comment]
Sounds great! Happy to review PRs, and feel free to reach out if I can provide guidance on the codebase.

**Comment by kurtbuilds** [comment]
Closed with https://github.com/kurtbuilds/libninja/pull/7
